{{- /* templates/ingress-api.yaml */}}
{{- if .Values.wazuh.ingress.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wazuh.fullname" . }}-api
  {{- with .Values.wazuh.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.wazuh.ingress.className }}
  ingressClassName: {{ .Values.wazuh.ingress.className }}
  {{- end }}
  {{- if .Values.wazuh.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.wazuh.ingress.host | quote }}
      secretName: {{ .Values.wazuh.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.wazuh.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wazuh.fullname" . }}-master
                port:
                  number: {{ .Values.wazuh.master.service.ports.api }}
{{- end }}
