{{- if .Values.wazuh.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wazuh.fullname" . }}-agents
  {{- with .Values.wazuh.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.wazuh.ingress.className }}
  ingressClassName: {{ .Values.wazuh.ingress.className }}
  {{- end }}
  {{- if .Values.wazuh.ingress.tls }}
  tls:
    {{- toYaml .Values.wazuh.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.wazuh.ingress.host }}
      http:
        paths:
          - path: /registration
            pathType: Prefix
            backend:
              service:
                name: wazuh
                port:
                  number: {{ .Values.wazuh.master.service.ports.registration }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wazuh
                port:
                  number: {{ .Values.wazuh.master.service.ports.api }}
          - path: /agent-events
            pathType: Prefix
            backend:
              service:
                name: {{ include "wazuh.fullname" . }}-manager-worker
                port:
                  number: {{ .Values.wazuh.worker.service.ports.agentEvents }}
{{- end }}